#old_sound_rabbit_mq:
#    connections:
#        default:
#            url: '%env(RABBITMQ_URL)%'
#    producers:
#        # use 'old_sound_rabbit_mq.task_producer' service to send data.
#        task:
#            connection:       default
#            exchange_options: { name: 'task', type: direct }
#    consumers:
#        task:
#            connection:       default
#            exchange_options: { name: 'task', type: direct }
#            queue_options:    { name: 'task'}
#            callback:         App\Consumer\TaskConsumer
old_sound_rabbit_mq:
    connections:
        default:
            host:     '172.19.0.1'
            port:     5672
            user:     'guest'
            password: 'guest'
#            vhost:    '/'
            lazy:     false
            connection_timeout: 6
            read_write_timeout: 6
            url: '%env(RABBITMQ_URL)%'

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false

            # requires php-amqplib v2.4.1+
            heartbeat: 0

            #requires php_sockets.dll
            use_socket: true # default false
        another:
            # A different (unused) connection defined by an URL. One can omit all parts,
            # except the scheme (amqp:). If both segment in the URL and a key value (see above)
            # are given the value from the URL takes precedence.
            # See https://www.rabbitmq.com/uri-spec.html on how to encode values.
            url: 'amqp://guest:guest@172.19.0.1:5672/?lazy=1&connection_timeout=6'
    producers:
        upload_file:
            class: App\Producer\UploadProducer
            connection:       default
            exchange_options: {name: 'upload-file', type: direct}
#            service_alias:    rabbitmq_app_service # no alias by default
            auto_setup_fabric: false
    consumers:
        upload_file:
            connection:       default
            exchange_options: {name: 'upload-file', type: direct}
            queue_options:    {name: 'upload-file'}
            callback:         app.consumer.upload
            qos_options: { prefetch_size: 0, prefetch_count: 1, global: false }
            idle_timeout: 60
            idle_timeout_exit_code: 0
            timeout_wait: 10
            auto_setup_fabric: false